/**
 * Session Intelligence: Weekly Reel Generator (SI-09)
 * 
 * Generates progress reels from weekly summaries
 * Reuses existing carousel-based reel system from PR19
 * Triggered after weekly summary creation
 */

import * as admin from 'firebase-admin';
import * as logger from 'firebase-functions/logger';
import { redactForProgressReel } from '../ai/piiRedaction';
import { createReferralInternal } from '../growth/referralHandler';

const db = admin.firestore();

export interface WeeklyReelData {
  reelId: string;
  userId: string;
  conversationId: string;
  weekId: string; // "2025-W01"
  startDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD
  highlights: string[]; // PII-redacted
  aggregatedSummary: string; // PII-redacted narrative
  qualityScore: number; // Derived from activity
  sentiment: 'positive' | 'neutral' | 'negative';
  topics: string[]; // Subject topics covered
  totalRecordings: number;
  totalDuration: number; // seconds
  imageUrls: string[]; // Generated by frontend carousel
  referralLink: string;
  createdAt: admin.firestore.Timestamp;
  expiresAt: admin.firestore.Timestamp; // 30 days
  status: 'ready' | 'generating' | 'failed';
}

/**
 * Calculate quality score from weekly activity
 * Based on: recording count, duration, consistency
 */
function calculateWeeklyQualityScore(
  totalRecordings: number,
  totalDuration: number, // seconds
  dailySummaries: any[]
): number {
  // Base score from activity volume
  let score = 0;
  
  // Recording count (max 40 points)
  // 5+ recordings = 40 points
  score += Math.min(totalRecordings * 8, 40);
  
  // Total duration (max 30 points)
  // 3+ hours = 30 points
  const hours = totalDuration / 3600;
  score += Math.min(hours * 10, 30);
  
  // Consistency (max 30 points)
  // Active days (days with at least 1 recording)
  const activeDays = dailySummaries.filter(d => d.recordingCount > 0).length;
  score += Math.min(activeDays * 5, 30);
  
  // Cap at 100
  return Math.min(Math.round(score), 100);
}

/**
 * Determine sentiment from weekly activity
 */
function determineWeeklySentiment(
  qualityScore: number,
  totalRecordings: number
): 'positive' | 'neutral' | 'negative' {
  if (qualityScore >= 75 && totalRecordings >= 5) {
    return 'positive';
  } else if (qualityScore >= 50 || totalRecordings >= 3) {
    return 'neutral';
  } else {
    return 'negative';
  }
}

/**
 * Generate a progress reel from a weekly summary
 * 
 * Flow:
 * 1. Fetch weekly summary
 * 2. Check consent for sharing
 * 3. Redact PII from highlights and summary
 * 4. Calculate quality score
 * 5. Create referral link
 * 6. Save reel document
 * 
 * @param conversationId - Conversation ID
 * @param weekId - Week ID (YYYY-WW)
 * @returns Reel ID
 */
export async function generateWeeklyReel(
  conversationId: string,
  weekId: string
): Promise<string | null> {
  logger.info('🎬 Generating weekly reel', {
    conversationId: conversationId.substring(0, 12),
    weekId,
  });
  
  try {
    // Step 1: Fetch weekly summary
    const weeklySummaryRef = db
      .collection('summaries')
      .doc(conversationId)
      .collection('weekly')
      .doc(weekId);
    
    const weeklySummaryDoc = await weeklySummaryRef.get();
    
    if (!weeklySummaryDoc.exists) {
      logger.warn('⚠️ Weekly summary not found', { conversationId, weekId });
      return null;
    }
    
    const weeklySummary = weeklySummaryDoc.data() as any;
    
    // Step 2: Get conversation participants to determine user
    const conversationDoc = await db.collection('conversations').doc(conversationId).get();
    
    if (!conversationDoc.exists) {
      logger.warn('⚠️ Conversation not found', { conversationId });
      return null;
    }
    
    const conversation = conversationDoc.data();
    const participants = conversation?.participants || [];
    
    if (participants.length === 0) {
      logger.warn('⚠️ No participants in conversation', { conversationId });
      return null;
    }
    
    // For now, use first participant as the user
    // In a real implementation, you might want to generate reels for all parents
    const userId = participants[0];
    
    // Step 3: Check consent
    const userDoc = await db.collection('users').doc(userId).get();
    const hasConsent = userDoc.data()?.consents?.progressSharing === true;
    
    if (!hasConsent) {
      logger.info('⚠️ Weekly reel skipped - no consent', {
        userId: userId.substring(0, 8),
        conversationId: conversationId.substring(0, 12),
        weekId,
      });
      return null;
    }
    
    // Step 4: Redact PII from highlights and summary
    const redactedHighlights = (weeklySummary.highlights || []).map((h: string) =>
      redactForProgressReel(h)
    );
    
    const redactedSummary = redactForProgressReel(weeklySummary.aggregatedSummary || '');
    
    logger.info('🔒 PII redaction complete', {
      conversationId: conversationId.substring(0, 12),
      weekId,
      originalHighlights: weeklySummary.highlights?.length || 0,
      redactedHighlights: redactedHighlights.length,
    });
    
    // Step 5: Calculate quality score
    const qualityScore = calculateWeeklyQualityScore(
      weeklySummary.totalRecordings || 0,
      weeklySummary.totalDuration || 0,
      weeklySummary.dailySummaries || []
    );
    
    const sentiment = determineWeeklySentiment(
      qualityScore,
      weeklySummary.totalRecordings || 0
    );
    
    logger.info('📊 Quality metrics calculated', {
      conversationId: conversationId.substring(0, 12),
      weekId,
      qualityScore,
      sentiment,
    });
    
    // Step 6: Create referral link
    const referralData = await createReferralInternal({
      referrerId: userId,
      referrerType: 'parent',
      targetType: 'parent',
      loopType: 'progress_reel',
      metadata: {
        conversationId,
        weekId,
        qualityScore,
        sentiment,
        source: 'weekly_summary',
      },
    });
    
    // Step 7: Create reel document
    const reelId = `reel_weekly_${weekId}_${conversationId.substring(0, 8)}_${Date.now()}`;
    const now = Date.now();
    const expiresAt = admin.firestore.Timestamp.fromDate(
      new Date(now + 30 * 24 * 60 * 60 * 1000) // 30 days
    );
    
    const reelData: WeeklyReelData = {
      reelId,
      userId,
      conversationId,
      weekId,
      startDate: weeklySummary.startDate,
      endDate: weeklySummary.endDate,
      highlights: redactedHighlights,
      aggregatedSummary: redactedSummary,
      qualityScore,
      sentiment,
      topics: weeklySummary.topicsSet || [],
      totalRecordings: weeklySummary.totalRecordings || 0,
      totalDuration: weeklySummary.totalDuration || 0,
      imageUrls: [], // Generated by frontend carousel
      referralLink: referralData.url,
      createdAt: admin.firestore.Timestamp.now(),
      expiresAt,
      status: 'ready',
    };
    
    await db.collection('reels').doc(reelId).set(reelData);
    
    // Step 8: Update weekly summary with reel reference
    await weeklySummaryRef.update({
      reelUrl: reelId, // Using reelId as the reference
      reelStatus: 'complete',
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });
    
    logger.info('✅ Weekly reel generated successfully', {
      reelId,
      userId: userId.substring(0, 8),
      conversationId: conversationId.substring(0, 12),
      weekId,
      highlightCount: redactedHighlights.length,
      qualityScore,
      sentiment,
      expiresIn: '30 days',
    });
    
    return reelId;
    
  } catch (error: any) {
    logger.error('❌ Weekly reel generation failed', {
      conversationId: conversationId.substring(0, 12),
      weekId,
      error: error.message,
      stack: error.stack,
    });
    
    // Log to failed operations
    await db.collection('failed_operations').add({
      operation: 'weekly_reel_generation',
      conversationId,
      weekId,
      error: error.message,
      timestamp: admin.firestore.FieldValue.serverTimestamp(),
      retry: true,
    });
    
    return null;
  }
}

