import { generateHMAC, verifyHMAC } from './crypto';
import * as logger from 'firebase-functions/logger';

/**
 * Parameters for generating a referral link
 */
export interface ReferralLinkParams {
  referralId: string;
  referrerId: string;
  loopType: string;
  experimentId?: string;
  variantId?: string;
  channel?: string;
}

/**
 * Result from link generation
 */
export interface ReferralLinkResult {
  url: string;
  provider: 'firebase' | 'branch' | 'custom';
}

/**
 * Generate signed referral link
 * 
 * Provider priority:
 * 1. Firebase Dynamic Links (DEPRECATED - shut down Aug 2025)
 * 2. Branch.io (if configured)
 * 3. Custom short domain (fallback)
 * 
 * @param params - Link generation parameters
 * @returns Generated link and provider name
 */
export async function generateReferralLink(
  params: ReferralLinkParams
): Promise<ReferralLinkResult> {
  const startTime = Date.now();
  
  try {
    // Try Branch.io if configured
    if (process.env.BRANCH_KEY) {
      const branchLink = await generateBranchLink(params);
      if (branchLink) {
        logger.info('✅ Generated Branch.io link', {
          latency: Date.now() - startTime,
        });
        return { url: branchLink, provider: 'branch' };
      }
    }
  } catch (error: any) {
    logger.warn('⚠️ Branch.io link generation failed, using fallback', {
      error: error.message,
    });
  }
  
  // Fallback: Custom short link with HMAC signature
  const customLink = generateCustomShortLink(params);
  logger.info('✅ Generated custom short link', {
    latency: Date.now() - startTime,
  });
  
  return { url: customLink, provider: 'custom' };
}

/**
 * Generate Branch.io deep link
 * 
 * Branch.io provides:
 * - Cross-platform deep linking
 * - Install attribution
 * - Analytics dashboard
 * 
 * @param params - Link parameters
 * @returns Branch.io link or null if unavailable
 */
async function generateBranchLink(
  params: ReferralLinkParams
): Promise<string | null> {
  // TODO: Implement Branch.io SDK integration
  // Requires: branch-io-sdk npm package + Branch dashboard setup
  // For MVP, return null to use custom links
  
  // Example implementation:
  // const branch = require('branch-sdk');
  // const linkData = {
  //   data: {
  //     referralId: params.referralId,
  //     loopType: params.loopType,
  //     experimentId: params.experimentId,
  //   },
  // };
  // return await branch.link(linkData);
  
  return null; // Fallback to custom for MVP
}

/**
 * Generate custom short link with HMAC signature
 * 
 * Format: https://messageai.app/r/{referralId}?sig={hmac}&loop={loopType}
 * 
 * The signature prevents tampering:
 * - Users cannot modify referralId to steal credit
 * - Server verifies signature before accepting attribution
 * 
 * @param params - Link parameters
 * @returns Custom referral URL
 */
function generateCustomShortLink(params: ReferralLinkParams): string {
  const { referralId, loopType, experimentId, variantId, channel } = params;
  
  // Generate HMAC signature (sign referralId + loopType)
  // This prevents users from changing the referralId in the URL
  const dataToSign = `${referralId}:${loopType}`;
  const signature = generateHMAC(dataToSign);
  
  // Build URL with query params
  const baseUrl = process.env.REFERRAL_BASE_URL || 'https://messageai.app/r';
  const url = new URL(`${baseUrl}/${referralId}`);
  
  // Required params
  url.searchParams.set('sig', signature);
  url.searchParams.set('loop', loopType);
  
  // Optional params (for analytics)
  if (experimentId) url.searchParams.set('exp', experimentId);
  if (variantId) url.searchParams.set('var', variantId);
  if (channel) url.searchParams.set('ch', channel);
  
  return url.toString();
}

/**
 * Verify referral link signature
 * 
 * Ensures the link was generated by our server and hasn't been tampered with
 * 
 * @param referralId - Referral ID from URL
 * @param loopType - Loop type from URL
 * @param signature - HMAC signature from URL
 * @returns true if signature is valid
 */
export function verifyReferralLink(
  referralId: string,
  loopType: string,
  signature: string
): boolean {
  const dataToSign = `${referralId}:${loopType}`;
  return verifyHMAC(dataToSign, signature);
}

/**
 * Parse referral link and extract parameters
 * 
 * @param url - Full referral URL
 * @returns Parsed parameters or null if invalid
 */
export function parseReferralLink(url: string): {
  referralId: string;
  loopType: string;
  signature: string;
  experimentId?: string;
  variantId?: string;
  channel?: string;
} | null {
  try {
    const parsed = new URL(url);
    
    // Extract referralId from path (e.g., /r/ref_123 -> ref_123)
    const pathParts = parsed.pathname.split('/');
    const referralId = pathParts[pathParts.length - 1];
    
    // Extract query params
    const signature = parsed.searchParams.get('sig');
    const loopType = parsed.searchParams.get('loop');
    
    if (!referralId || !signature || !loopType) {
      return null;
    }
    
    return {
      referralId,
      loopType,
      signature,
      experimentId: parsed.searchParams.get('exp') || undefined,
      variantId: parsed.searchParams.get('var') || undefined,
      channel: parsed.searchParams.get('ch') || undefined,
    };
  } catch (error) {
    logger.warn('⚠️ Failed to parse referral link', { url });
    return null;
  }
}

