/**
 * Progress Reel Generator
 * PR19: Progress Reels
 * 
 * Generates privacy-compliant progress reels from session summaries
 * Uses PII redaction and referral attribution
 * 
 * Features:
 * - PII redaction (names, schools, emails)
 * - Referral link generation
 * - 30-day auto-expiration
 * - Consent verification
 */

import * as admin from 'firebase-admin';
import * as logger from 'firebase-functions/logger';
import { redactForProgressReel } from '../ai/piiRedaction';
import { createReferralInternal } from './referralHandler';

const getDb = () => admin.firestore();

export interface GenerateReelOptions {
  sessionId: string;
  userId: string;
  summary: any; // SessionSummary from PR20
}

/**
 * Generate a privacy-compliant progress reel
 * 
 * Flow:
 * 1. Verify user has granted progressSharing consent
 * 2. Redact PII from session highlights
 * 3. Create referral link for attribution
 * 4. Save reel to Firestore with 30-day expiration
 * 
 * @param options - Generation options
 * @returns Reel ID
 * @throws Error if consent not granted or generation fails
 */
export async function generateProgressReel(
  options: GenerateReelOptions
): Promise<string> {
  const { sessionId, userId, summary } = options;
  const db = getDb();
  
  logger.info('🎬 Generating progress reel', { 
    sessionId,
    userId: userId.substring(0, 8),
    qualityScore: summary.qualityScore,
  });
  
  try {
    // Step 1: Check consent (COPPA/FERPA requirement)
    const userDoc = await db.collection('users').doc(userId).get();
    const hasConsent = userDoc.data()?.consents?.progressSharing === true;
    
    if (!hasConsent) {
      logger.warn('⚠️ Reel generation skipped - no consent', {
        userId: userId.substring(0, 8),
        sessionId,
      });
      throw new Error('User has not granted consent for progress sharing');
    }
    
    // Step 2: Redact PII from highlights
    const redactedHighlights = summary.highlights.map((h: string) => 
      redactForProgressReel(h)
    );
    
    logger.info('🔒 PII redaction complete', {
      sessionId,
      originalCount: summary.highlights.length,
      redactedCount: redactedHighlights.length,
    });
    
    // Step 3: Create referral link for attribution
    const referralData = await createReferralInternal({
      referrerId: userId,
      referrerType: 'parent',
      targetType: 'parent',
      loopType: 'progress_reel',
      metadata: { 
        sessionId, 
        qualityScore: summary.qualityScore,
        sentiment: summary.sentiment,
      },
    });
    
    // Step 4: Create reel document
    const reelId = `reel_${sessionId}_${Date.now()}`;
    const now = Date.now();
    const expiresAt = admin.firestore.Timestamp.fromDate(
      new Date(now + 30 * 24 * 60 * 60 * 1000) // 30 days
    );
    
    const reelData = {
      reelId,
      userId,
      sessionId,
      highlights: redactedHighlights,
      qualityScore: summary.qualityScore,
      sentiment: summary.sentiment,
      imageUrls: [], // Generated by frontend carousel
      referralLink: referralData.url,
      createdAt: admin.firestore.Timestamp.now(),
      expiresAt,
      status: 'ready',
    };
    
    await db.collection('reels').doc(reelId).set(reelData);
    
    logger.info('✅ Progress reel generated successfully', {
      reelId,
      userId: userId.substring(0, 8),
      sessionId,
      highlightCount: redactedHighlights.length,
      expiresIn: '30 days',
    });
    
    return reelId;
    
  } catch (error: any) {
    logger.error('❌ Progress reel generation failed', {
      sessionId,
      userId: userId.substring(0, 8),
      error: error.message,
      stack: error.stack,
    });
    
    // Log to failed operations for manual retry
    await db.collection('failed_operations').add({
      operation: 'progress_reel_generation',
      sessionId,
      userId,
      error: error.message,
      timestamp: admin.firestore.FieldValue.serverTimestamp(),
      retry: true,
    });
    
    throw error;
  }
}

